version: "2"
services:
  service-registry:
    build: service-registry/
    ports:
      - "8761:8761"
    volumes:
      - /tmp/log/service-registry:/log
  gateway:
    build: gateway/
    ports:
      - "8080:8080"
    links:
      - service-registry
    volumes:
      - /tmp/log/gateway:/log
  monitor:
    build: monitor/
    ports:
      - "8180:8080"
    links:
      - service-registry
    volumes:
      - /tmp/log/monitor:/log
  git-ssh-server:
    image: unixtastic/git-ssh-server
    ports:
      - "2222:22"
    volumes:
      - "/tmp/git:/git"
  configuration:
    build: configuration/
    ports:
      - "8280:8080"
    links:
      - service-registry
      - git-ssh-server
  hello-world:
    build: hello-world/
    links:
      - service-registry
      - configuration
    volumes:
      - /tmp/log/hello-world:/log
  primes:
    build: primes/
    links:
      - service-registry
      - configuration
    volumes:
      - /tmp/log/primes:/log
