version: '2'
services:
  eureka-service:
    image: eureka-service
    ports:
      - "8761:8761"
  eureka-client:
    image: eureka-client
    ports:
      - "8080:8080"
    links:
      - eureka-service
  helloworld:
    image: helloworld
    ports:
      - "18080:8080"
    links:
      - eureka-service
  primes:
    image: primes
    ports:
      - "28080:8080"
    links:
      - eureka-service

